### ISSUE TITLE
Uncaught TypeError: Cannot read property 'write' of undefined

### ISSUE THREAD

**Issue by hedani** [Tizzio/clipboard-api#1]
Have you test this on a server?
Locally it work but on the server I got this message ('Uncaught TypeError: Cannot read property 'write' of undefined'). The issue refer to navigator.clipboard.write([item]);

Chrome: Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by adriano-t** [comment]
> Have you test this on a server?
> Locally it work but on the server I got this message ('Uncaught TypeError: Cannot read property 'write' of undefined'). The issue refer to navigator.clipboard.write([item]);
> 
> Chrome: Version 78.0.3904.97 (Official Build) (64-bit)

What do you mean with "on the server"?
The issue is given by the fact that "navigator.clipboard" is undefined, but i think i can't help you without informations

**Comment by hedani** [comment]
Thanks for your reply. The code that you shared works fine "locally" but when I host it on a server (ftp) get error  ('Uncaught TypeError: Cannot read property 'write' of undefined'). The issue refer to navigator.clipboard.write([item])
